apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- github.com/Yolean/kubernetes-assert/runtime-nodejs/kustomize?ref=930ee2627ac53b7e356ce6a317226a010ffe3c8d
namePrefix: example-project-
commonLabels:
  app: example-project
images:
- name: yolean/assert-runtime-nodejs
  newName: builds-registry.ystack.svc.cluster.local/yolean/kubernetes-assert/example-project
